CREATE CATALOG IF NOT EXISTS nyc_mobility;

USE CATALOG nyc_mobility;
CREATE SCHEMA IF NOT EXISTS nyc_bronze;
CREATE SCHEMA IF NOT EXISTS nyc_silver;
CREATE SCHEMA IF NOT EXISTS nyc_gold;
CREATE SCHEMA IF NOT EXISTS nyc_quality;
